### ISSUE TITLE
extract_aesPCS error data undefined cloumn

### ISSUE THREAD

**Issue by lizhongliu1996** [gabrielodom/pathwayPCA#31]
after create omics, running extract_pcs shows error message that "error in [data.frame(object@assayData_df, x)]" undefined columns selected.

stop("undefined columns selected")

**Comment by gabrielodom** [comment]
Did you check the `Odom_test_20180928.R` script? I explained the error there. Please take a look at our vignettes:
https://gabrielodom.github.io/pathwayPCA/articles/C1-Quickstart_Guide.html

The code and examples are from the master branch of the package, which is what you can download from GitHub.

**Comment by lizhongliu1996** [comment]
> Did you check the `Odom_test_20180928.R` script? I explained the error there. Please take a look at our vignettes:
> https://gabrielodom.github.io/pathwayPCA/articles/C1-Quickstart_Guide.html
> 
> The code and examples are from the master branch of the package, which is what you can download from GitHub.

yes, I chech the r script, but I don't have a different signatures database, so how can I just do PCA to the assay data, find PC1 of each column?

**Comment by gabrielodom** [comment]
1. Your data had samples as the columns the last time I looked at it. Therefore, the "PC1 of each column" doesn't make mathematical sense.
2. If you transposed your data so that the columns were the CpGs, finding the "PC1 of each column" *still* does not make mathematical sense because the PC of each feature is itself.
3. Without a collection of clustered CpGs, such as from `Aclust()`, you cannot extract PCs from a CpG cluster. The package is called `pathwayPCA`: it **requires** clusters or pathways of features to work.

Please come to our development meeting on Monday (at 3PM). We can discuss this more then.
