### ISSUE TITLE
error for AESPCA and SuperPCA examples

### ISSUE THREAD

**Issue by lxw391** [gabrielodom/pathwayPCA#47]
I got an error when I tried to test AESPCA, see attached
[error_for_AESPCA.docx](https://github.com/gabrielodom/pathwayPCA/files/2592058/error_for_AESPCA.docx)

**Comment by gabrielodom** [comment]
Similar error for `SuperPCA_pVals()`. Looking into it.

**Comment by gabrielodom** [comment]
In this example, we create an `OmicsSurv` object directly with the `CreateOmicsSurv()` function, rather than the user-facing `CreateOmics()` function. The error is because the validity of the assay data and pathway collection objects are checked in the `CreateOmics()` wrapper, while assuming that these objects have already been checked before any calls to the `CreateOmics*()` functions. We probably need to update that example, but the bug remains. I need to move validity checking for pathway collections to the `CreateOmics*()` functions.

**Comment by gabrielodom** [comment]
Problem: less of a code issue and more of an input issue.

Possible solutions:
a. change the `CreateOmics*()` functions to check and clean the incoming objects (they are currently checked and cleaned in `CreateOmics()`), OR
b. update the examples and help files for the `CreateOmics*()` functions to point the users back to the `CreateOmics()` wrapper

Implemented solution:
I've removed all mentions of the `CreateOmics*()` functions from the help files. All help hyperlinks now point to the `CreateOmics()` wrapper.
